sudo: required
dist: trusty
cache:
  - bundler
#before_script:
#- bundle exec rake db:create
#- bundle exec rake db:migrate
#- bundle exec rake assets:precompile
install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
#    sudo apt-get -o Dpkg::Options::="--force-confdef" \
 #    -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
 - bundle exec rake db:create
 - bundle exec rake db:migrate
 - bundle exec rake assets:precompile
 - docker-compose up --build -d


after_script:
- docker-compose down
